name: Generate Snake

on:
  # run automatically at 00:00 UTC every day
  schedule:
    - cron: "0 0 * * *"
  # run manually from the Actions tab if you ever need to
  workflow_dispatch:

permissions:
  contents: write            # allow the workflow to push the file

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Generate SVG snake
        uses: Platane/snk@v3
        with:
          github_user_name: DanEstok           # <<-- your username
          outputs: |
            dist/github-contribution-grid-snake.svg

      - name: Commit & push if the file changed
        uses: EndBug/add-and-commit@v9
        with:
          default_author: github_actions
          message: "chore: update contribution snake"
          add: "dist/*.svg"
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      - name: Publish to “output” branch
        uses: peaceiris/actions-gh-pages@v4
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_branch: output
          publish_dir: ./dist
          keep_files: true
